/*

    Part 2

    Important Source : https://sinalalenakhsh.notion.site/1-Chat-GPT-310ba8a7e074493e95d8c45bfe6aed86

   Notion Source: https://sinalalenakhsh.notion.site/13-first-project-job-offer-Part-2-f1e5cedf8257483a8ccc75780060e635

   از کاربر ورودی میگیره
   تحلیل روی اطلاعات کاربر انجام میده
   اگر اطلاعات مطابق نظرش بود
   خروجی رو به کاربر نمایش میده
   اگر اطلاعات مطابق نظرش نبود
   یک خروجی ثابت رو به کاربر نمایش میده

       داستان کاریابی در آلمان

   variables:
       userName            string
       jobTitle            string
       userAge             int
       yearsExperience     int

   we will if condition

*/

package main

import (
	"bufio"
	"fmt"
	"os"
	"strings"
)

func main() {
	var userName, jobTitle string

	reader := bufio.NewReader(os.Stdin)

	fmt.Println("Welcome to the program to help immigrants to Germany!")
	fmt.Println("Please enter your personal and job-related information.")

	fmt.Print("What's You full name? ")
	userName, _ = reader.ReadString('\n')
	userName = strings.TrimSuffix(userName, "\n")

	fmt.Printf("Hello %v \n", userName)

	fmt.Print("What do you looking for job? ")
	jobTitle, _ = reader.ReadString('\n')
	jobTitle = strings.TrimSuffix(jobTitle, "\n")

	if jobTitles[jobTitle] {
		fmt.Printf("Congratulations %v, one job is ON for this: %v\n", userName, jobTitle)
	} else {
		fmt.Printf("Sorry %v, %v is not a valid job title.\n", userName, jobTitle)
	}

}

var jobTitles = map[string]bool{
	"Software Engineer":                       true,
	"Data Analyst":                            true,
	"Product Manager":                         true,
	"UI/UX Designer":                          true,
	"Accountant":                              true,
	"Sales Representative":                    true,
	"Marketing Specialist":                    true,
	"Human Resources Manager":                 true,
	"Project Manager":                         true,
	"Customer Support Specialist":             true,
	"Business Analyst":                        true,
	"Operations Manager":                      true,
	"Financial Analyst":                       true,
	"Administrative Assistant":                true,
	"Legal Assistant":                         true,
	"Medical Assistant":                       true,
	"Graphic Designer":                        true,
	"Copywriter":                              true,
	"Content Creator":                         true,
	"Social Media Manager":                    true,
	"Digital Marketing Manager":               true,
	"Video Editor":                            true,
	"Photographer":                            true,
	"Chef":                                    true,
	"Waiter/Waitress":                         true,
	"Bartender":                               true,
	"Hotel Receptionist":                      true,
	"Tour Guide":                              true,
	"Flight Attendant":                        true,
	"Pilot":                                   true,
	"Mechanical Engineer":                     true,
	"Electrical Engineer":                     true,
	"Civil Engineer":                          true,
	"Chemical Engineer":                       true,
	"Aerospace Engineer":                      true,
	"Environmental Engineer":                  true,
	"Biomedical Engineer":                     true,
	"Pharmacist":                              true,
	"Dentist":                                 true,
	"Physician":                               true,
	"Nurse":                                   true,
	"Physical Therapist":                      true,
	"Occupational Therapist":                  true,
	"Psychologist":                            true,
	"Social Worker":                           true,
	"Elementary School Teacher":               true,
	"High School Teacher":                     true,
	"University Professor":                    true,
	"Librarian":                               true,
	"Architect":                               true,
	"Interior Designer":                       true,
	"Landscape Architect":                     true,
	"Real Estate Agent":                       true,
	"Property Manager":                        true,
	"Mortgage Loan Officer":                   true,
	"Investment Banker":                       true,
	"Financial Advisor":                       true,
	"Insurance Agent":                         true,
	"Stockbroker":                             true,
	"Private Equity Analyst":                  true,
	"Management Consultant":                   true,
	"Account Manager":                         true,
	"Supply Chain Manager":                    true,
	"Logistics Coordinator":                   true,
	"Quality Control Inspector":               true,
	"Maintenance Technician":                  true,
	"Electrician":                             true,
	"Plumber":                                 true,
	"Carpenter":                               true,
	"Mason":                                   true,
	"Painter":                                 true,
	"Landscaper":                              true,
	"Gardener":                                true,
	"Security Guard":                          true,
	"Police Officer":                          true,
	"Firefighter":                             true,
	"Paramedic":                               true,
	"Veterinarian":                            true,
	"Zookeeper":                               true,
	"Wildlife Biologist":                      true,
	"Marine Biologist":                        true,
	"Geologist":                               true,
	"Astrophysicist":                          true,
	"Astronomer":                              true,
	"Mathematician":                           true,
	"Statistician":                            true,
	"Economist":                               true,
	"Sociologist":                             true,
	"Anthropologist":                          true,
	"Political Scientist":                     true,
	"Historian":                               true,
	"Journalist":                              true,
	"Public Relations Specialist":             true,
	"Lawyer":                                  true,
	"Judge":                                   true,
	"Paralegal":                               true,
	"Translator":                              true,
	"Interpreter":                             true,
	"Actuary":                                 true,
	"Acupuncturist":                           true,
	"Advertising Manager":                     true,
	"Agricultural Engineer":                   true,
	"Agricultural Scientist":                  true,
	"Air Traffic Controller":                  true,
	"Aircraft Mechanic":                       true,
	"Aircraft Pilot":                          true,
	"Airline Customer Service Agent":          true,
	"Airline Flight Attendant":                true,
	"Alcohol and Drug Counselor":              true,
	"Animator":                                true,
	"Art Director":                            true,
	"Athletic Trainer":                        true,
	"Attorney":                                true,
	"Auditor":                                 true,
	"Auto Mechanic":                           true,
	"Automotive Body Repairer":                true,
	"Avionics Technician":                     true,
	"Baker":                                   true,
	"Bank Teller":                             true,
	"Barber":                                  true,
	"Behavioral Health Technician":            true,
	"Bicycle Mechanic":                        true,
	"Biophysicist":                            true,
	"Bookkeeping Clerk":                       true,
	"Brick Mason":                             true,
	"Bridge and Tunnel Officer":               true,
	"Broadcast News Analyst":                  true,
	"Budget Analyst":                          true,
	"Building Inspector":                      true,
	"Bus Driver":                              true,
	"Business Manager":                        true,
	"Cable Installer":                         true,
	"Cafeteria Cook":                          true,
	"Call Center Representative":              true,
	"Camera Operator":                         true,
	"Cardiovascular Technologist":             true,
	"Carpet Installer":                        true,
	"Cartographer":                            true,
	"Cashier":                                 true,
	"Chemist":                                 true,
	"Childcare Worker":                        true,
	"Chiropractor":                            true,
	"Claims Adjuster":                         true,
	"Clergy":                                  true,
	"Clinical Laboratory Technician":          true,
	"Clinical Psychologist":                   true,
	"Coating Inspector":                       true,
	"Commercial Diver":                        true,
	"Communications Equipment Operator":       true,
	"Community Health Worker":                 true,
	"Computer Network Architect":              true,
	"Computer Programmer":                     true,
	"Computer Support Specialist":             true,
	"Construction Laborer":                    true,
	"Construction Manager":                    true,
	"Cook":                                    true,
	"Cosmetologist":                           true,
	"Cost Estimator":                          true,
	"Counselor":                               true,
	"Court Clerk":                             true,
	"Craft Artist":                            true,
	"Crane Operator":                          true,
	"Credit Analyst":                          true,
	"Criminal Investigator":                   true,
	"Crop Farmer":                             true,
	"Custom Tailor":                           true,
	"Customer Service Representative":         true,
	"Dancer":                                  true,
	"Database Administrator":                  true,
	"Dental Assistant":                        true,
	"Dental Hygienist":                        true,
	"Desktop Publisher":                       true,
	"Diagnostic Medical Sonographer":          true,
	"Dietitian":                               true,
	"Dining Room and Cafeteria Attendant":     true,
	"Director of Photography":                 true,
	"Drafter":                                 true,
	"Drywall and Ceiling Tile Installer":      true,
	"Editor":                                  true,
	"Education Administrator":                 true,
	"Electric Motor and Tool Repairer":        true,
	"Electrical and Electronics Drafter":      true,
	"Electronic Equipment Installer":          true,
	"Elevator Installer and Repairer":         true,
	"Emergency Management Director":           true,
	"Emergency Medical Technician":            true,
	"Energy Auditor":                          true,
	"Engineering Manager":                     true,
	"English Language and Literature Teacher": true,
	"Environmental Scientist":                 true,
	"Epidemiologist":                          true,
	"Event Planner":                           true,
	"Excavating Machine Operator":             true,
	"Executive Assistant":                     true,
	"Exercise Physiologist":                   true,
	"Exhibit Designer":                        true,
	"Expeditor":                               true,
	"Fabric Mender":                           true,
	"Family Practitioner":                     true,
	"Farmer":                                  true,
	"Fashion Designer":                        true,
	"Fence Erector":                           true,
	"Field Auditor":                           true,
	"File Clerk":                              true,
	"Film and Video Editor":                   true,
	"Financial Examiner":                      true,
	"Financial Manager":                       true,
	"Financial Specialist":                    true,
	"Fire Inspector":                          true,
	"Fish and Game Warden":                    true,
	"Fitness Trainer":                         true,
	"Flight Engineer":                         true,
	"Floral Designer":                         true,
	"Food and Tobacco Roasting, Baking, and Drying Machine Operator": true,
	"Food Preparation Worker":                         true,
	"Food Science Technician":                         true,
	"Food Service Manager":                            true,
	"Foreign Language and Literature Teacher":         true,
	"Forensic Science Technician":                     true,
	"Forest and Conservation Technician":              true,
	"Forester":                                        true,
	"Fundraiser":                                      true,
	"Funeral Attendant":                               true,
	"Funeral Director":                                true,
	"Furniture Finisher":                              true,
	"Gaming Dealer":                                   true,
	"Gaming Manager":                                  true,
	"Gaming Supervisor":                               true,
	"Gaming Surveillance Officer":                     true,
	"Gas Compressor and Gas Pumping Station Operator": true,
	"General and Operations Manager":                  true,
	"Genetic Counselor":                               true,
	"Geographer":                                      true,
	"Geological and Petroleum Technician":             true,
	"Geoscientist":                                    true,
	"Glazier":                                         true,
	"Government Property Inspector and Investigator":  true,
	"Graduate Teaching Assistant":                     true,
	"Grounds Maintenance Worker":                      true,
	"Hairdresser":                                     true,
	"Hand Sewer":                                      true,
	"Hazardous Materials Removal Worker":              true,
	"Health Educator":                                 true,
	"Health Information Technician":                   true,
	"Health Services Manager":                         true,
	"Healthcare Social Worker":                        true,
	"Heating, Air Conditioning, and Refrigeration Mechanic": true,
	"Heavy and Tractor-trailer Truck Driver":                true,
	"Historical Archivist":                                  true,
	"Home Appliance Repairer":                               true,
	"Home Health Aide":                                      true,
	"Horticulturist":                                        true,
	"Hospitality Manager":                                   true,
	"Human Factors Engineer":                                true,
	"Human Resources Assistant":                             true,
	"Human Resources Specialist":                            true,
	"Hydrologist":                                           true,
	"Illustrator":                                           true,
	"Industrial Designer":                                   true,
	"Industrial Engineer":                                   true,
	"Industrial Machinery Mechanic":                         true,
	"Industrial Production Manager":                         true,
	"Information Clerk":                                     true,
	"Information Security Analyst":                          true,
	"Instructional Coordinator":                             true,
	"Instrumentation Technician":                            true,
	"Insulation Worker":                                     true,
	"Insurance Appraiser":                                   true,
	"Insurance Claims Clerk":                                true,
	"Insurance Sales Agent":                                 true,
	"Insurance Underwriter":                                 true,
	"Interpreter and Translator":                            true,
	"Interviewer":                                           true,
	"Investment Fund Manager":                               true,
	"Iron and Steel Worker":                                 true,
	"Janitor":                                               true,
	"Jeweler":                                               true,
	"Judicial Law Clerk":                                    true,
	"Kindergarten Teacher":                                  true,
	"Law Clerk":                                             true,
	"Law Enforcement Teacher":                               true,
	"Law Teacher":                                           true,
	"Layout Worker":                                         true,
	"Leather Worker":                                        true,
	"Legal Secretary":                                       true,
	"Library Assistant":                                     true,
	"Library Science Teacher":                               true,
	"Library Technician":                                    true,
	"Licensed Practical Nurse (LPN)":                        true,
	"Licensed Vocational Nurse (LVN)":                       true,
	"Life Scientist":                                        true,
	"Lighthouse Keeper":                                     true,
	"Loading Machine Operator":                              true,
	"Loan Counselor":                                        true,
	"Loan Officer":                                          true,
	"Locker Room Attendant":                                 true,
	"Locksmith":                                             true,
	"Locomotive Engineer":                                   true,
	"Locomotive Firer":                                      true,
	"Log Grader and Scaler":                                 true,
	"Logging Equipment Operator":                            true,
	"Logging Worker":                                        true,
	"Logistician":                                           true,
	"Machine Feeder and Offbearer":                          true,
	"Machine Tool Operator":                                 true,
	"Machinery Maintenance Worker":                          true,
	"Mail Clerk":                                            true,
	"Mail Machine Operator":                                 true,
	"Maintenance and Repair Worker":                         true,
	"Makeup Artist":                                         true,
	"Management Analyst":                                    true,
	"Manager":                                               true,
	"Manager of Air Crew":                                   true,
	"Manager of Food Preparation and Serving Worker":        true,
	"Manager of Landscaping, Lawn Service, and Groundskeeping Worker": true,
	"Manager of Mechanics":                                    true,
	"Manager of Personal Service Worker":                      true,
	"Manager of Police and Detective":                         true,
	"Manager of Production Worker":                            true,
	"Manager of Transportation Worker":                        true,
	"Manager of Weapons Specialists":                          true,
	"Manufactured Building and Mobile Home Installer":         true,
	"Mapping Technician":                                      true,
	"Marble Setter":                                           true,
	"Marine Engineer":                                         true,
	"Marine Oiler":                                            true,
	"Market Research Analyst":                                 true,
	"Marketing Manager":                                       true,
	"Marriage and Family Therapist":                           true,
	"Massage Therapist":                                       true,
	"Material Moving Worker":                                  true,
	"Materials Engineer":                                      true,
	"Materials Scientist":                                     true,
	"Mathematical Science Teacher":                            true,
	"Meat Packer":                                             true,
	"Meat, Poultry, and Fish Cutter":                          true,
	"Mechanical Door Repairer":                                true,
	"Mechanical Drafter":                                      true,
	"Mechanical Engineering Technician":                       true,
	"Medical and Clinical Laboratory Technologist":            true,
	"Medical and Clinical Laboratory Technician":              true,
	"Medical and Health Services Manager":                     true,
	"Medical Appliance Technician":                            true,
	"Medical Equipment Preparer":                              true,
	"Medical Equipment Repairer":                              true,
	"Medical Records Technician":                              true,
	"Medical Scientist":                                       true,
	"Medical Secretary":                                       true,
	"Medical Transcriptionist":                                true,
	"Meeting, Convention, and Event Planner":                  true,
	"Mental Health Counselor":                                 true,
	"Merchandise Displayer":                                   true,
	"Metal Fabricator":                                        true,
	"Metal Molding, Coremaking, and Casting Machine Operator": true,
	"Metal-Refining Furnace Operator":                         true,
	"Meter Reader":                                            true,
	"Microbiologist":                                          true,
	"Middle School Teacher":                                   true,
	"Milling and Planing Machine Setter, Operator":            true,
	"Millwright":                                              true,
	"Mine Cutting Machine Operator":                           true,
	"Mining Engineer":                                         true,
	"Mining Machine Operator":                                 true,
	"Mixing and Blending Machine Operator":                    true,
	"Mobile Heavy Equipment Mechanic":                         true,
	"Model Maker":                                             true,
	"Mold Maker":                                              true,
	"Molder":                                                  true,
	"Motion Picture Projectionist":                            true,
	"Motorboat Mechanic":                                      true,
	"Motorcycle Mechanic":                                     true,
	"Municipal Clerk":                                         true,
	"Municipal Court Clerk":                                   true,
	"Municipal Fire Fighter":                                  true,
	"Municipal Fire Fighting and Prevention Supervisor":       true,
	"Museum Technician":                                       true,
	"Music Arranger and Orchestrator":                         true,
	"Music Director":                                          true,
	"Music Teacher":                                           true,
	"Musician":                                                true,
	"Natural Sciences Manager":                                true,
	"Naval Architect":                                         true,
	"Network and Computer Systems Administrator":              true,
	"Network and Computer Systems Analyst":                    true,
	"New Accounts Clerk":                                      true,
	"News Analyst, Reporter and Correspondent":                true,
	"Nonfarm Animal Caretaker":                                true,
	"Nuclear Engineer":                                        true,
	"Nuclear Medicine Technologist":                           true,
	"Nuclear Power Reactor Operator":                          true,
	"Nuclear Technician":                                      true,
	"Nursing Aide":                                            true,
	"Nursing Instructor":                                      true,
	"Nursing Psychiatric Aide":                                true,
	"Nutritionist":                                            true,
	"Obstetrician":                                            true,
	"Occupational Health and Safety Specialist":               true,
	"Occupational Health and Safety Technician":               true,
	"Occupational Therapy Aide":                               true,
	"Occupational Therapy Assistant":                          true,
	"Office and Administrative Support Worker":                true,
	"Office Clerk":                                            true,
	"Office Machine and Cash Register Servicer":               true,
	"Office Manager":                                          true,
	"Operating Engineer":                                      true,
	"Operations Research Analyst":                             true,
	"Ophthalmic Laboratory Technician":                        true,
	"Optician":                                                true,
	"Optometrist":                                             true,
	"Order Clerk":                                             true,
	"Order Filler":                                            true,
	"Orthodontist":                                            true,
	"Orthotist and Prosthetist":                               true,
	"Outdoor Power Equipment Mechanic":                        true,
	"Packaging and Filling Machine Operator":                  true,
	"Painting, Coating, and Decorating Worker":                true,
	"Paper Goods Machine Setter, Operator":                    true,
	"Paperhanger":                                             true,
	"Paralegal and Legal Assistant":                           true,
	"Park Naturalist":                                         true,
	"Parking Enforcement Worker":                              true,
	"Parking Lot Attendant":                                   true,
	"Parts Salesperson":                                       true,
	"Paving, Surfacing, and Tamping Equipment Operator":       true,
	"Payroll and Timekeeping Clerk":                           true,
	"Pediatrician":                                            true,
	"Personal Care Aide":                                      true,
	"Personal Financial Advisor":                              true,
	"Pest Control Worker":                                     true,
	"Petroleum Engineer":                                      true,
	"Petroleum Pump System Operator, Refinery Operator, and Gauger": true,
	"Pharmacy Aide":                                            true,
	"Pharmacy Technician":                                      true,
	"Philosophy and Religion Teacher":                          true,
	"Photogrammetrist":                                         true,
	"Photographic Process Worker":                              true,
	"Physical Scientist":                                       true,
	"Physical Therapist Aide":                                  true,
	"Physical Therapist Assistant":                             true,
	"Physician Assistant":                                      true,
	"Physicist":                                                true,
	"Physics Teacher":                                          true,
	"Pile-Driver Operator":                                     true,
	"Pipe Fitter":                                              true,
	"Pipe Laying and Pipefitting Contractor":                   true,
	"Pipelayer":                                                true,
	"Plant and System Operator":                                true,
	"Plasterer and Stucco Mason":                               true,
	"Plastic Molding and Casting Machine Operator":             true,
	"Podiatrist":                                               true,
	"Police and Sheriff's Patrol Officer":                      true,
	"Police Detective":                                         true,
	"Political Science Teacher":                                true,
	"Postal Service Clerk":                                     true,
	"Postal Service Mail Carrier":                              true,
	"Postal Service Mail Sorter":                               true,
	"Postmaster and Mail Superintendent":                       true,
	"Power Distributor and Dispatcher":                         true,
	"Power Generating Plant Operator":                          true,
	"PR Specialist":                                            true,
	"Precision Instrument and Equipment Repairer":              true,
	"Prepress Technician and Worker":                           true,
	"Preschool Education Administrator":                        true,
	"Preschool Teacher":                                        true,
	"Press and Press Brake Machine Setter, Operator":           true,
	"Printing Press Operator":                                  true,
	"Private Detective and Investigator":                       true,
	"Probation Officer":                                        true,
	"Procurement Clerk":                                        true,
	"Producer and Director":                                    true,
	"Product Management Leader":                                true,
	"Product Safety Engineer":                                  true,
	"Production Control Clerk":                                 true,
	"Production Manager":                                       true,
	"Production Planner and Scheduler":                         true,
	"Production Worker":                                        true,
	"Professional Photographer":                                true,
	"Professor":                                                true,
	"Program Director":                                         true,
	"Proofreader and Copy Marker":                              true,
	"Property, Real Estate, and Community Association Manager": true,
	"Prosthetic Technician":                                    true,
}
